Inser, Delete, Update and GUI are done :)

diff --git a/DBMS b/DBMS
--- a/DBMS
+++ b/DBMS
@@ -1,4 +1,5 @@
 #!/bin/bash 
+
 shopt -s extglob
 export LC_COLLATE=C
 
@@ -19,7 +20,7 @@ function Create_DB
         zenity --info --title="success" --text="Database $DBname has been created successfully :)" --no-wrap
     fi
 
-    MainDB
+    #MainDB
 }
 
 function Open_DB
@@ -35,7 +36,7 @@ function Open_DB
         zenity --error --title="Error!" --text="$DBname doesn't exist!" --no-wrap
     fi
 
-    MainDB
+    #MainDB
 }
 
 function Drop_DB
@@ -43,9 +44,9 @@ function Drop_DB
     ReadDBNameFromUSer
     if [ -d $DBname ]
     then 
-        input=`(whiptail --title "Are you sure you want to delete this Database?" --fb --menu "Confirm" 15 50 6 \
+        input=$(whiptail --title "Are you sure you want to delete this Database?" --fb --menu "Confirm" 15 50 6 \
             "1" "yes" \
-            "2" "no"  3>&1 1>&2 2>&3)`
+            "2" "no"  3>&1 1>&2 2>&3)
             case $input in
                     1 )  rm -r $DBname
                          zenity --info --title="Success" --text="$DBname has been removed successfully" --no-wrap
@@ -58,7 +59,7 @@ function Drop_DB
         zenity --error --title="Error!" --text="$DBname doesn't exist!" --no-wrap
     fi  
 
-    MainDB       
+    #MainDB       
 }
 
 function list_DBs
@@ -72,13 +73,13 @@ function list_DBs
         zenity --error --title="Error!" --text="No Databases to show!" --no-wrap
     fi
 
-    MainDB 
+    #MainDB 
 }
 
 #### Auxiliary function, Reading Database name from the user ####################
 function ReadDBNameFromUSer
 {
-    DBname=`(whiptail --inputbox "Enter Database name" 8 39  --title "Database" 3>&1 1>&2 2>&3)`
+    DBname=$(whiptail --inputbox "Enter Database name" 8 39  --title "Database" 3>&1 1>&2 2>&3)
 }
 
 ##################################  Tables level ###############################################
@@ -86,8 +87,8 @@ function ReadDBNameFromUSer
 function List_All_Tables
 {
     ls > .listOftables
-    whiptail --textbox .listOftables 12 80 --title "Available Tables"
-    MainTables
+    whiptail --title "Available Tables" --fb --scrolltext --textbox .listOftables 12 80
+    #MainTables
 }
 
 function Open_Certain_table
@@ -95,23 +96,23 @@ function Open_Certain_table
     ReadTableNameFromUSer
     if [ -f $Tablename ]
     then
+        #cat $Tablename
         Record_stage $Tablename
     else
         zenity --error --title="Error!" --text="$Tablename doesn't exist!" --no-wrap
     fi
 
-    MainTables
+    #MainTables
 }
 
-function DescribeTable
-{
-    cat $Tablename > .TableContent
-    whiptail --textbox .TableContent 12 80 --title "$Tablename"
-    Record_stage
-}
 function Create_table
 {
     ReadTableNameFromUSer
+    seperator="|"
+    raw_seperator="\n"
+    pkey=""
+    declare columnsNumber
+    declare -A metaData_data
     if [ -f $Tablename ]
     then
         zenity --error --title="Error!" --text="$Tablename already exist!" --no-wrap
@@ -119,31 +120,26 @@ function Create_table
         
         while ! [[ $columnsNumber =~ ^[0-9]+$ ]]
         do
-           columnsNumber=`(whiptail --inputbox "Enter Number of Columns" 8 39 3>&1 1>&2 2>&3)`
+           columnsNumber=$(whiptail --inputbox "Enter Number of Columns" 8 39 3>&1 1>&2 2>&3)
         done
-
-        seperator="|"
-        raw_seperator="\n"
-        pkey=""
 
         metaData_def="Column Name"$seperator"Type"$seperator"Primary Key"
         
         showNumber=1
-        declare -A metaData_data
         for (( counter = 0; counter < $columnsNumber; counter++ ));
         do
             _counter=0
             #echo -e "Name of Column Number "$showNumber": \c"
             #read columnName
-            columnName=`(whiptail --inputbox "Enter Name of Column Number $showNumber" 8 39 3>&1 1>&2 2>&3)`
+            columnName=$(whiptail --inputbox "Enter Name of Column Number $showNumber" 8 39 3>&1 1>&2 2>&3)
             ((showNumber++))
             data[$counter]=$columnName
             metaData_data[$counter,$_counter]=$columnName # metaData_data[0,0] = id
             ((_counter++))
 
-            input=`(whiptail --title "Type of Column $columnName" --fb --menu "Choose data type" 15 50 6 \
+            input=$(whiptail --title "Type of Column $columnName" --fb --menu "Choose data type" 15 50 6 \
             "1" "integer" \
-            "2" "string"  3>&1 1>&2 2>&3)`
+            "2" "string"  3>&1 1>&2 2>&3)
             case $input in
                     1 ) 
                         columnType="int"
@@ -155,12 +151,12 @@ function Create_table
 
             metaData_data[$counter,$_counter]=$columnType # metaData_data[0,1] = type(int or str)
             ((_counter++))
-
+             zenity --error --title="Error!" --text="$pKey here!" --no-wrap
             if [[ $pKey == "" ]]; 
             then
-                input=`(whiptail --title "Would you like to set as Primary Key ?" --fb --menu "Set a PK" 15 50 6 \
+                input=$(whiptail --title "Would you like to set as Primary Key ?" --fb --menu "Set a PK" 15 50 6 \
                 "1" "yes" \
-                "2" "no"  3>&1 1>&2 2>&3)`
+                "2" "no"  3>&1 1>&2 2>&3)
                 case $input in
                      1 ) pKey="PK"; metaData_data[$counter,$_counter]="$pKey";
                         ;;
@@ -213,8 +209,8 @@ function Create_table
         else
             zenity --error --title="Error" --text="NOT Successful Creation of Table $Tablename ! \n You must set a column as a primary key" --no-wrap
         fi
-    fi      
-    MainTables
+    fi   
+    unset pKey   
 }
 
 function Drop_table
@@ -222,9 +218,9 @@ function Drop_table
     ReadTableNameFromUSer
     if [ -f $Tablename ]
     then 
-        input=`(whiptail --title "Are you sure you want to delete this table?" --fb --menu "Confirm" 15 50 6 \
+        input=$(whiptail --title "Are you sure you want to delete this table?" --fb --menu "Confirm" 15 50 6 \
             "1" "yes" \
-            "2" "no"  3>&1 1>&2 2>&3)`
+            "2" "no"  3>&1 1>&2 2>&3)
             case $input in
                     1 )  rm $Tablename .$Tablename
                          zenity --info --title="Success" --text="$Tablename Table has been removed successfully :)" --no-wrap
@@ -237,12 +233,17 @@ function Drop_table
         zenity --error --title="Error!" --text="$Tablename Table doesn't exist!" --no-wrap
     fi  
 
-    MainTables
+   # MainTables
+}
+function DescribeTable
+{
+    cat $Tablename > .TableContent
+    whiptail --title "$Tablename" --fb --scrolltext --textbox .TableContent 12 80
 }
 #### Auxiliary function, Reading table name from the user #################### 
 function ReadTableNameFromUSer
 {
-    Tablename=`(whiptail --inputbox "Enter Table name" 8 39 3>&1 1>&2 2>&3)`
+    Tablename=$(whiptail --inputbox "Enter Table name" 8 39 3>&1 1>&2 2>&3)
 }
 
 ################################# Record level #########################################
@@ -267,7 +268,7 @@ function InsertInto
          colType=`(awk -F'|' '{if(NR=='$idx') print $2 }' .$Tablename)` 
          colConstraint=`(awk -F'|' '{if(NR=='$idx') print $3}' .$Tablename)`
          #data=$(zenity --entry --title="Enter data of column $colName")
-         data=`(whiptail --inputbox "Enter data of column $colName" 8 39 3>&1 1>&2 2>&3)`
+         data=$(whiptail --inputbox "Enter data of column $colName" 8 39 3>&1 1>&2 2>&3)
          #Validate data type 
          if [[ "$colType" == "str" ]]   
          then
@@ -280,7 +281,7 @@ function InsertInto
               *)
                  zenity --error --title="Error!" --text="Invalid data type! \n " --no-wrap
                  #data=$(zenity --entry --title="Enter valid data type (string)")
-                 data=`(whiptail --inputbox "Enter valid data type (string)" 8 39 3>&1 1>&2 2>&3)`
+                 data=$(whiptail --inputbox "Enter valid data type (string)" 8 39 3>&1 1>&2 2>&3)
                  ;;
               esac
             done
@@ -305,7 +306,7 @@ function InsertInto
                                         then
                                             zenity --error --title="Error!" --text="PK already exists! \n " --no-wrap
                                             #data=$(zenity --entry --title="Enter unique PK")
-                                            data=`(whiptail --inputbox "Enter unique Primary key" 8 39 3>&1 1>&2 2>&3)`
+                                            data=$(whiptail --inputbox "Enter unique Primary key" 8 39 3>&1 1>&2 2>&3)
                                             exist=0
                                         else 
                                             break 
@@ -316,7 +317,7 @@ function InsertInto
                         ;;
                     *) zenity --error --title="Error!" --text="Invalid data type! \n " --no-wrap
                         #data=$(zenity --entry --title="Enter valid data type (int)")
-                        data=`(whiptail --inputbox "Enter valid data type (int)" 8 39 3>&1 1>&2 2>&3)`
+                        data=$(whiptail --inputbox "Enter valid data type (int)" 8 39 3>&1 1>&2 2>&3)
                         ;;
                     esac
             done
@@ -349,21 +350,22 @@ function delete_record
    Tablename=$1
    let idx=2
    #pk=$(zenity --entry --title="Enter PK of the record you want to delete")
-   pk=`(whiptail --inputbox "Enter PK of the record you want to delete" 8 39 3>&1 1>&2 2>&3)`
-   noOfCol=`(awk -F: 'END{print NR}' .$Tablename)`
+   pk=$(whiptail --inputbox "Enter PK of the record you want to delete" 8 39 3>&1 1>&2 2>&3)
+   noOfCol=$(awk -F: 'END{print NR}' .$Tablename)
    until [ $idx -gt $noOfCol ]
     do
-         colConstraint=`(awk -F'|' '{if(NR=='$idx') print $3}' .$Tablename)`
+         colConstraint=$(awk -F'|' '{if(NR=='$idx') print $3}' .$Tablename)
          if [[ "$colConstraint" == "PK" ]]
         then
-            # GET the Record number using the PK
-            recordnumber=`(awk -F'|' '{if('$pk'==$('$idx'-1)) print NR}' $Tablename)`
+            # GET the Record number using the PK 
+            #check the entered Pk with all values by feild number 'idx'-1
+            recordnumber=$(awk -F'|' '{if($('$idx'-1)=='$pk') print NR}' $Tablename)
             # Check if the entered PK exist? "Delete" : "not found!" 
             if [[ "$recordnumber" =~ ^[0-9]+$ ]]
             then
-                 input=`(whiptail --title "Are you sure you want to delete this record?" --fb --menu "Confirm deletion" 15 50 6 \
+                 input=$(whiptail --title "Are you sure you want to delete this record?" --fb --menu "Confirm deletion" 15 50 6 \
                 "1" "yes" \
-                "2" "no"  3>&1 1>&2 2>&3)`
+                "2" "no"  3>&1 1>&2 2>&3)
                 case $input in
                         1 ) 
                             # Delete the record using the record number, then redirect to a new file and rename its name with table name :)
@@ -391,15 +393,88 @@ function delete_record
     done
 }
 
+function Update_cell
+{
+   Tablename=$1
+   let idx=2
+   updateType=""
+   let colFound=0
+   colName=""
+   declare pk
+   declare recordnumber
+   declare colname=$(whiptail --inputbox "Enter column name you want to update" 8 39 3>&1 1>&2 2>&3)
+   declare noOfCol=$(awk -F: 'END{print NR}' .$Tablename)
+
+   input=$(whiptail --title "Would you like to update by primary key ?" --fb --menu "Update options" 15 50 6 \
+        "1" "yes" \
+        "2" "no"  3>&1 1>&2 2>&3)
+        case $input in
+                1 ) updateType="y"
+                    pk=$(whiptail --inputbox "Enter PK of the record you want to update" 8 39 3>&1 1>&2 2>&3)
+                    newValue=$(whiptail --inputbox "Enter new value" 8 39 3>&1 1>&2 2>&3)
+                ;;
+                2 ) updateType="n"
+                    oldValue=$(whiptail --inputbox "Enter old value" 8 39 3>&1 1>&2 2>&3)
+                    newValue=$(whiptail --inputbox "Enter new value" 8 39 3>&1 1>&2 2>&3)
+                ;;
+        esac
+   until [ $idx -gt $noOfCol ]
+    do
+        colName=$(awk -F'|' '{if(NR=='$idx') print $1}' .$Tablename)
+        colConstraint=$(awk -F'|' '{if(NR=='$idx') print $3}' .$Tablename)
+
+        if [[ "$updateType" == "y" ]]
+        then
+            if [[ "$colConstraint" == "PK" ]]
+            then
+                recordnumber=$(awk -F'|' '{if($('$idx'-1)=='$pk') print NR}' $Tablename)
+                if ! [[ "$recordnumber" =~ ^[0-9]+$ ]]
+                then
+                      zenity --error --title="Error!" --text="$pk doesn't exist!" --no-wrap
+                      break 
+
+                fi
+            fi
+        fi
+
+        if [[ "$colName" == "$colname" ]]
+        then
+                ((colFound++))
+                if [[ "$colConstraint" == "PK" ]]
+                then
+                        zenity --error --title="Error!" --text="It is not allowed to update a Primary key" --no-wrap
+                        break
+                fi
+                
+                if [[ "$updateType" == "n"  ]]
+                then
+                    awk -F'|' -v new=$newValue -v old=$oldValue '$('$idx'-1)==old {$('$idx'-1)=new} {print}' OFS='|' $Tablename > tmp && mv tmp $Tablename
+                else        
+                     awk -F'|' -v new=$newValue 'NR=='$recordnumber'{$('$idx'-1)=new} {print}' OFS='|' $Tablename > tmp && mv tmp $Tablename
+                fi
+             
+            break
+        fi
+
+    ((idx++))
+    done
+    if [[ $colFound -gt 0 ]]
+    then 
+        zenity --info --title="Success!" --text="Cell updated successfully" --no-wrap
+    else
+        zenity --info --title="Success!" --text="$colname doesn't exist!" --no-wrap
+    fi
+
+}
 function MainDB
 {  
-
-    input=`(whiptail --title "Database Menu" --fb --menu "Choose an option" 15 50 6 \
+    while input=$(whiptail --title "Database Menu" --menu "Choose an option" 15 50 6 \
     "1" "Create Database" \
     "2" "Open Database" \
     "3" "Drop Database"  \
     "4" "List Database"   \
-    "5" "Exit" 3>&1 1>&2 2>&3)`
+    "5" "Exit" 3>&1 1>&2 2>&3 )
+    do
     case $input in
             1 ) 
                 Create_DB
@@ -417,17 +492,19 @@ function MainDB
                 clear; exit 0
             ;;
     esac
+    done
 }
 
 function MainTables
 {
-    input=`(whiptail --title "Tables Menu" --fb --menu "Choose an option" 15 50 6 \
-    "1" "List All Tables" \
-    "2" "Open Certain Table" \
-    "3" "Create Table"  \
-    "4" "Drop Table"   \
-    "5" "Back to DB Menu" \
-    "6" "Exit" 3>&1 1>&2 2>&3)`
+    while input=$(whiptail --title "Tables Menu" --menu "Choose an option" 15 50 6 \
+    "1" "List All Tables"  \
+    "2" "Open Certain Table"  \
+    "3" "Create Table"   \
+    "4" "Drop Table"    \
+    "5" "Back to DB Menu"  \
+    "6" "Exit" 3>&1 1>&2 2>&3)
+    do
     case $input in
             1 ) List_All_Tables 
             ;;
@@ -442,20 +519,22 @@ function MainTables
             6 ) clear; exit 0
             ;;
     esac
+    done
 }
 function Record_stage
 {
     Tablename=$1
-    input=`(whiptail --title "Records Menu" --fb --menu "Choose an option" 15 50 6 \
-    "1" "Show table" \
-    "2" "Insert New Record" \
-    "3" "Delete Record" \
+    while input=$(whiptail --title "Records Menu" --menu "Choose an option" 15 50 6 \
+     "1" "Show table" \
+    "2" "Insert New Record"  \
+    "3" "Delete Record"  \
     "4" "Update Certain Cell"  \
     "5" "Back to Tables Menu"   \
-    "6" "Exit" 3>&1 1>&2 2>&3)`
+    "6" "Exit" 3>&1 1>&2 2>&3 )
+    do  #read input
     case $input in
             1 ) DescribeTable $Tablename
-            ;;  
+            ;;
             2 ) InsertInto $Tablename
             ;;
             3 ) delete_record $Tablename
@@ -467,8 +546,10 @@ function Record_stage
             6 ) clear; exit 0
             ;;
     esac
+    done
     
 }
 
 
 MainDB
+
