Insert is updated

diff --git a/DBMS b/DBMS
--- a/DBMS
+++ b/DBMS
@@ -267,47 +267,48 @@ function InsertInto
          colName=`(awk -F'|' '{if(NR=='$idx') print $1}' .$Tablename)`
          colType=`(awk -F'|' '{if(NR=='$idx') print $2 }' .$Tablename)` 
          colConstraint=`(awk -F'|' '{if(NR=='$idx') print $3}' .$Tablename)`
-         #data=$(zenity --entry --title="Enter data of column $colName")
          data=$(whiptail --inputbox "Enter data of column $colName" 8 39 3>&1 1>&2 2>&3)
          #Validate data type 
          if [[ "$colType" == "str" ]]   
          then
            while [[ true ]]
             do
-             case $data in
-             +([a-z A-Z]) )
-                  break
-                  ;;
-              *)
-                 zenity --error --title="Error!" --text="Invalid data type! \n " --no-wrap
-                 #data=$(zenity --entry --title="Enter valid data type (string)")
-                 data=$(whiptail --inputbox "Enter valid data type (string)" 8 39 3>&1 1>&2 2>&3)
-                 ;;
-              esac
+                if [[ -z "$data" ]]
+                then
+                      zenity --error --title="Error!" --text="Empty string! \n " --no-wrap
+                      data=$(whiptail --inputbox "Enter valid data (string)" 8 39 3>&1 1>&2 2>&3)
+                else 
+                    case $data in
+                        +([a-zA-Z]) )
+                            break
+                            ;;
+                        *)
+                            zenity --error --title="Error!" --text="Invalid data type! \n " --no-wrap
+                            data=$(whiptail --inputbox "Enter valid data type (string)" 8 39 3>&1 1>&2 2>&3)
+                            ;;
+                        esac
+                fi
             done
          elif [[ "$colType" == "int" ]]
          then
-           while [[ true ]]
+           while ! [[ data =~ ^[0-9]+$ ]]
             do
-                    case $data in 
+                case $data in 
                     +([0-9]) )
                             # Check if the entered PK already exists
                                 if [[ "$colConstraint" == "PK" ]]
                                 then
                                     flag2=1
-                                    let exist=0
-                                    while [[ true ]]
+                                    while ! [[ data =~ ^[0-9]+$ ]]
                                     do
-                                        #set -x
+                                        declare exist=0
                                         exist=`(awk -F'|' '{if('$data'==$('$idx'-1)) print $('$idx'-1)}' $Tablename)` 
-                                        #echo $exist
-                                        #set +x
-                                        if ! [[ $exist -eq 0 ]]
+
+                                        if ! [[ $exist -eq 0  ]]
                                         then
                                             zenity --error --title="Error!" --text="PK already exists! \n " --no-wrap
-                                            #data=$(zenity --entry --title="Enter unique PK")
                                             data=$(whiptail --inputbox "Enter unique Primary key" 8 39 3>&1 1>&2 2>&3)
-                                            exist=0
+                                            unset exist
                                         else 
                                             break 
                                         fi
